databases:
  - name: carRental  
    databaseName: carrental_aqup
    user: carrental_aqup_user

services:
  - type: web
    name: car-rental-api
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: carrental_aqup
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false